name: prepare-release

on:
  workflow_dispatch:
    # Allows manually triggering release via
    # https://github.com/informalsystems/apalache/actions?query=workflow%3A%22Prepare+Release%22
    inputs:
      release_version:
        description: "Version (leave empty to increment patch version)"
        required: false
        default: ""
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Automatically prepare a minor version release every Monday
    - cron: "* * * * 1"

jobs:
  prepare-release:
    env:
      RELEASE_VERSION: ${{ github.event.inputs.release_version }}
      GITHUB_TOKEN: ${{ secrets.APALACHE_BOT_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Configure Git
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "github@actions.ci"
      - name: Prepare release
        run: |
          # FIXME
          POST_BODY=false ./script/release-prepare.sh
      - name: Upload release artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release-artifacts
          if-no-files-found: error
          path: |
            mod-distribution/target/apalache-pkg-*-full.jar
            release-commit-sha
