name: release

on:
  pull_request:
    branches: [unstable]

jobs:
  cut-release:
    # Trigger only on merge of [release] pull request
    if: startsWith(github.event.pull_request.title, '[release]')
    # FIXME
    # && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cut Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HEAD_REF: ${{ github.head_ref }}
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "github@actions.ci"
          git branch
          git log -3
          echo $HEAD_REF
          git checkout $HEAD_REF~1
          git log -1
          git status

  # FIXME
  # ./script/release-publish.sh
